name: Deploy to GitHub Pages  

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  # Runs CI when PRs are opened or updated

jobs:
  deploy:
    name: Build & Deploy  
    runs-on: ubuntu-latest  

    permissions:
      pages: write     
      id-token: write  

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Repo  
        uses: actions/checkout@v4

      - name: Create Node Environment  
        uses: actions/setup-node@v4
        with: 
          node-version: 16.x
          
      - name: Delete Old Artifacts (Optional)
        run: |
          rm -rf ./dist

      - name: Install Packages and Build Application  
        run: |
          npm ci
          npm run build

      - name: Upload GitHub Pages Artifact  
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  
          path: dist/         
          
      - name: Download GitHub Pages Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: dist/

      - name: Deploy to GitHub Pages  
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
        env:
          ACTIONS_STEP_DEBUG: true 
